// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: product_reader_messages.proto

package readerService

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductID     string                 `protobuf:"bytes,1,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=Price,proto3" json:"Price,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_product_reader_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_product_reader_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_product_reader_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetProductID() string {
	if x != nil {
		return x.ProductID
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Product) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductID     string                 `protobuf:"bytes,1,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=Price,proto3" json:"Price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductReq) Reset() {
	*x = CreateProductReq{}
	mi := &file_product_reader_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductReq) ProtoMessage() {}

func (x *CreateProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_reader_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductReq.ProtoReflect.Descriptor instead.
func (*CreateProductReq) Descriptor() ([]byte, []int) {
	return file_product_reader_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProductReq) GetProductID() string {
	if x != nil {
		return x.ProductID
	}
	return ""
}

func (x *CreateProductReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductReq) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type CreateProductResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductID     string                 `protobuf:"bytes,1,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductResp) Reset() {
	*x = CreateProductResp{}
	mi := &file_product_reader_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductResp) ProtoMessage() {}

func (x *CreateProductResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_reader_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductResp.ProtoReflect.Descriptor instead.
func (*CreateProductResp) Descriptor() ([]byte, []int) {
	return file_product_reader_messages_proto_rawDescGZIP(), []int{2}
}

func (x *CreateProductResp) GetProductID() string {
	if x != nil {
		return x.ProductID
	}
	return ""
}

type UpdateProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductID     string                 `protobuf:"bytes,1,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=Price,proto3" json:"Price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductReq) Reset() {
	*x = UpdateProductReq{}
	mi := &file_product_reader_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductReq) ProtoMessage() {}

func (x *UpdateProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_reader_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductReq.ProtoReflect.Descriptor instead.
func (*UpdateProductReq) Descriptor() ([]byte, []int) {
	return file_product_reader_messages_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateProductReq) GetProductID() string {
	if x != nil {
		return x.ProductID
	}
	return ""
}

func (x *UpdateProductReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProductReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProductReq) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type UpdateProductResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductID     string                 `protobuf:"bytes,1,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductResp) Reset() {
	*x = UpdateProductResp{}
	mi := &file_product_reader_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductResp) ProtoMessage() {}

func (x *UpdateProductResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_reader_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductResp.ProtoReflect.Descriptor instead.
func (*UpdateProductResp) Descriptor() ([]byte, []int) {
	return file_product_reader_messages_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateProductResp) GetProductID() string {
	if x != nil {
		return x.ProductID
	}
	return ""
}

type GetProductByIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductID     string                 `protobuf:"bytes,1,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductByIdReq) Reset() {
	*x = GetProductByIdReq{}
	mi := &file_product_reader_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductByIdReq) ProtoMessage() {}

func (x *GetProductByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_reader_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductByIdReq.ProtoReflect.Descriptor instead.
func (*GetProductByIdReq) Descriptor() ([]byte, []int) {
	return file_product_reader_messages_proto_rawDescGZIP(), []int{5}
}

func (x *GetProductByIdReq) GetProductID() string {
	if x != nil {
		return x.ProductID
	}
	return ""
}

type GetProductByIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=Product,proto3" json:"Product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductByIdResp) Reset() {
	*x = GetProductByIdResp{}
	mi := &file_product_reader_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductByIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductByIdResp) ProtoMessage() {}

func (x *GetProductByIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_reader_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductByIdResp.ProtoReflect.Descriptor instead.
func (*GetProductByIdResp) Descriptor() ([]byte, []int) {
	return file_product_reader_messages_proto_rawDescGZIP(), []int{6}
}

func (x *GetProductByIdResp) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type SearchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Search        string                 `protobuf:"bytes,1,opt,name=Search,proto3" json:"Search,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchReq) Reset() {
	*x = SearchReq{}
	mi := &file_product_reader_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchReq) ProtoMessage() {}

func (x *SearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_reader_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchReq.ProtoReflect.Descriptor instead.
func (*SearchReq) Descriptor() ([]byte, []int) {
	return file_product_reader_messages_proto_rawDescGZIP(), []int{7}
}

func (x *SearchReq) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *SearchReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type SearchResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCount    int64                  `protobuf:"varint,1,opt,name=TotalCount,proto3" json:"TotalCount,omitempty"`
	TotalPages    int64                  `protobuf:"varint,2,opt,name=TotalPages,proto3" json:"TotalPages,omitempty"`
	Page          int64                  `protobuf:"varint,3,opt,name=Page,proto3" json:"Page,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=Size,proto3" json:"Size,omitempty"`
	HasMore       bool                   `protobuf:"varint,5,opt,name=HasMore,proto3" json:"HasMore,omitempty"`
	Products      []*Product             `protobuf:"bytes,6,rep,name=Products,proto3" json:"Products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResp) Reset() {
	*x = SearchResp{}
	mi := &file_product_reader_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResp) ProtoMessage() {}

func (x *SearchResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_reader_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResp.ProtoReflect.Descriptor instead.
func (*SearchResp) Descriptor() ([]byte, []int) {
	return file_product_reader_messages_proto_rawDescGZIP(), []int{8}
}

func (x *SearchResp) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *SearchResp) GetTotalPages() int64 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *SearchResp) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchResp) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SearchResp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *SearchResp) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type DeleteProductByIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductID     string                 `protobuf:"bytes,1,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductByIdReq) Reset() {
	*x = DeleteProductByIdReq{}
	mi := &file_product_reader_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductByIdReq) ProtoMessage() {}

func (x *DeleteProductByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_reader_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductByIdReq.ProtoReflect.Descriptor instead.
func (*DeleteProductByIdReq) Descriptor() ([]byte, []int) {
	return file_product_reader_messages_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteProductByIdReq) GetProductID() string {
	if x != nil {
		return x.ProductID
	}
	return ""
}

type DeleteProductByIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductByIdResp) Reset() {
	*x = DeleteProductByIdResp{}
	mi := &file_product_reader_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductByIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductByIdResp) ProtoMessage() {}

func (x *DeleteProductByIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_product_reader_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductByIdResp.ProtoReflect.Descriptor instead.
func (*DeleteProductByIdResp) Descriptor() ([]byte, []int) {
	return file_product_reader_messages_proto_rawDescGZIP(), []int{10}
}

var File_product_reader_messages_proto protoreflect.FileDescriptor

const file_product_reader_messages_proto_rawDesc = "" +
	"\n" +
	"\x1dproduct_reader_messages.proto\x12\rreaderService\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe7\x01\n" +
	"\aProduct\x12\x1c\n" +
	"\tProductID\x18\x01 \x01(\tR\tProductID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12 \n" +
	"\vDescription\x18\x03 \x01(\tR\vDescription\x12\x14\n" +
	"\x05Price\x18\x04 \x01(\x01R\x05Price\x128\n" +
	"\tCreatedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tUpdatedAt\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\"|\n" +
	"\x10CreateProductReq\x12\x1c\n" +
	"\tProductID\x18\x01 \x01(\tR\tProductID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12 \n" +
	"\vDescription\x18\x03 \x01(\tR\vDescription\x12\x14\n" +
	"\x05Price\x18\x04 \x01(\x01R\x05Price\"1\n" +
	"\x11CreateProductResp\x12\x1c\n" +
	"\tProductID\x18\x01 \x01(\tR\tProductID\"|\n" +
	"\x10UpdateProductReq\x12\x1c\n" +
	"\tProductID\x18\x01 \x01(\tR\tProductID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12 \n" +
	"\vDescription\x18\x03 \x01(\tR\vDescription\x12\x14\n" +
	"\x05Price\x18\x04 \x01(\x01R\x05Price\"1\n" +
	"\x11UpdateProductResp\x12\x1c\n" +
	"\tProductID\x18\x01 \x01(\tR\tProductID\"1\n" +
	"\x11GetProductByIdReq\x12\x1c\n" +
	"\tProductID\x18\x01 \x01(\tR\tProductID\"F\n" +
	"\x12GetProductByIdResp\x120\n" +
	"\aProduct\x18\x01 \x01(\v2\x16.readerService.ProductR\aProduct\"K\n" +
	"\tSearchReq\x12\x16\n" +
	"\x06Search\x18\x01 \x01(\tR\x06Search\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"\xc2\x01\n" +
	"\n" +
	"SearchResp\x12\x1e\n" +
	"\n" +
	"TotalCount\x18\x01 \x01(\x03R\n" +
	"TotalCount\x12\x1e\n" +
	"\n" +
	"TotalPages\x18\x02 \x01(\x03R\n" +
	"TotalPages\x12\x12\n" +
	"\x04Page\x18\x03 \x01(\x03R\x04Page\x12\x12\n" +
	"\x04Size\x18\x04 \x01(\x03R\x04Size\x12\x18\n" +
	"\aHasMore\x18\x05 \x01(\bR\aHasMore\x122\n" +
	"\bProducts\x18\x06 \x03(\v2\x16.readerService.ProductR\bProducts\"4\n" +
	"\x14DeleteProductByIdReq\x12\x1c\n" +
	"\tProductID\x18\x01 \x01(\tR\tProductID\"\x17\n" +
	"\x15DeleteProductByIdRespB\x12Z\x10./;readerServiceb\x06proto3"

var (
	file_product_reader_messages_proto_rawDescOnce sync.Once
	file_product_reader_messages_proto_rawDescData []byte
)

func file_product_reader_messages_proto_rawDescGZIP() []byte {
	file_product_reader_messages_proto_rawDescOnce.Do(func() {
		file_product_reader_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_reader_messages_proto_rawDesc), len(file_product_reader_messages_proto_rawDesc)))
	})
	return file_product_reader_messages_proto_rawDescData
}

var file_product_reader_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_product_reader_messages_proto_goTypes = []any{
	(*Product)(nil),               // 0: readerService.Product
	(*CreateProductReq)(nil),      // 1: readerService.CreateProductReq
	(*CreateProductResp)(nil),     // 2: readerService.CreateProductResp
	(*UpdateProductReq)(nil),      // 3: readerService.UpdateProductReq
	(*UpdateProductResp)(nil),     // 4: readerService.UpdateProductResp
	(*GetProductByIdReq)(nil),     // 5: readerService.GetProductByIdReq
	(*GetProductByIdResp)(nil),    // 6: readerService.GetProductByIdResp
	(*SearchReq)(nil),             // 7: readerService.SearchReq
	(*SearchResp)(nil),            // 8: readerService.SearchResp
	(*DeleteProductByIdReq)(nil),  // 9: readerService.DeleteProductByIdReq
	(*DeleteProductByIdResp)(nil), // 10: readerService.DeleteProductByIdResp
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_product_reader_messages_proto_depIdxs = []int32{
	11, // 0: readerService.Product.CreatedAt:type_name -> google.protobuf.Timestamp
	11, // 1: readerService.Product.UpdatedAt:type_name -> google.protobuf.Timestamp
	0,  // 2: readerService.GetProductByIdResp.Product:type_name -> readerService.Product
	0,  // 3: readerService.SearchResp.Products:type_name -> readerService.Product
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_product_reader_messages_proto_init() }
func file_product_reader_messages_proto_init() {
	if File_product_reader_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_reader_messages_proto_rawDesc), len(file_product_reader_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_product_reader_messages_proto_goTypes,
		DependencyIndexes: file_product_reader_messages_proto_depIdxs,
		MessageInfos:      file_product_reader_messages_proto_msgTypes,
	}.Build()
	File_product_reader_messages_proto = out.File
	file_product_reader_messages_proto_goTypes = nil
	file_product_reader_messages_proto_depIdxs = nil
}
