// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: product_writer.proto

package writerService

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_product_writer_proto protoreflect.FileDescriptor

const file_product_writer_proto_rawDesc = "" +
	"\n" +
	"\x14product_writer.proto\x12\rwriterService\x1a\x1dproduct_writer_messages.proto2\x8b\x02\n" +
	"\rwriterService\x12Q\n" +
	"\rCreateProduct\x12\x1f.writerService.CreateProductReq\x1a\x1f.writerService.CreateProductRes\x12Q\n" +
	"\rUpdateProduct\x12\x1f.writerService.UpdateProductReq\x1a\x1f.writerService.UpdateProductRes\x12T\n" +
	"\x0eGetProductById\x12 .writerService.GetProductByIdReq\x1a .writerService.GetProductByIdResB\x12Z\x10./;writerServiceb\x06proto3"

var file_product_writer_proto_goTypes = []any{
	(*CreateProductReq)(nil),  // 0: writerService.CreateProductReq
	(*UpdateProductReq)(nil),  // 1: writerService.UpdateProductReq
	(*GetProductByIdReq)(nil), // 2: writerService.GetProductByIdReq
	(*CreateProductRes)(nil),  // 3: writerService.CreateProductRes
	(*UpdateProductRes)(nil),  // 4: writerService.UpdateProductRes
	(*GetProductByIdRes)(nil), // 5: writerService.GetProductByIdRes
}
var file_product_writer_proto_depIdxs = []int32{
	0, // 0: writerService.writerService.CreateProduct:input_type -> writerService.CreateProductReq
	1, // 1: writerService.writerService.UpdateProduct:input_type -> writerService.UpdateProductReq
	2, // 2: writerService.writerService.GetProductById:input_type -> writerService.GetProductByIdReq
	3, // 3: writerService.writerService.CreateProduct:output_type -> writerService.CreateProductRes
	4, // 4: writerService.writerService.UpdateProduct:output_type -> writerService.UpdateProductRes
	5, // 5: writerService.writerService.GetProductById:output_type -> writerService.GetProductByIdRes
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_product_writer_proto_init() }
func file_product_writer_proto_init() {
	if File_product_writer_proto != nil {
		return
	}
	file_product_writer_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_writer_proto_rawDesc), len(file_product_writer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_writer_proto_goTypes,
		DependencyIndexes: file_product_writer_proto_depIdxs,
	}.Build()
	File_product_writer_proto = out.File
	file_product_writer_proto_goTypes = nil
	file_product_writer_proto_depIdxs = nil
}
